; Build targets

[platformio]
default_envs = d1_mini

[env]
; Shared environment
platform = espressif8266
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs

lib_deps =
  crankyoldgit/IRremoteESP8266@2.9.0
  bblanchon/ArduinoJson@7.4.3
  tzapu/WiFiManager@2.0.17
  https://github.com/ESP32Async/ESPAsyncWebServer.git#v3.6.0
  https://github.com/ESP32Async/ESPAsyncTCP.git#v2.0.0

build_flags =
  -D PIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY
  -D VERSION=\"0.8.2\"
  -D ARDUINOJSON_ENABLE_DEPRECATED=0

build_src_flags =
  -Wall
  -Wextra
  -Werror=return-type

check_tool = cppcheck
check_src_filters = +<src/> -<.pio/>
check_skip_packages = yes
check_flags =
  cppcheck: --enable=warning,style,performance,portability
  cppcheck: --inline-suppr
  cppcheck: --suppress=preprocessorErrorDirective
  cppcheck: -i.pio
  cppcheck: -i.pio/libdeps

[env:d1_mini]
; Hardware profile for WeMos D1 mini
board = d1_mini

upload_speed = 921600

build_flags =
  ${env.build_flags}
  -D IR_SEND_PIN=4
  -D IR_RECEIVE_PIN=5
